"use strict";
const $ = (s) => document.querySelector(s);
const video = $("#preview"), canvas = $("#captureCanvas"), shutter = $("#shutterButton");
const state = { stream:null, deviceId:null, facing:"environment", sound:false, selected:null, photos:[], memoryOnly:false };
const dbPromise = new Promise((resolve, reject) => { const r=indexedDB.open("silent-camera",1); r.onupgradeneeded=()=>r.result.createObjectStore("photos",{keyPath:"id"}); r.onsuccess=()=>resolve(r.result); r.onerror=()=>reject(r.error); });
function tx(mode="readonly"){return dbPromise.then(db=>db.transaction("photos",mode).objectStore("photos"));}
async function readPhotos(){ const s=await tx(); return new Promise((res,rej)=>{const r=s.getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.created-a.created));r.onerror=()=>rej(r.error);}); }
async function putPhoto(photo){const s=await tx("readwrite"); return new Promise((res,rej)=>{const r=s.put(photo);r.onsuccess=res;r.onerror=()=>rej(r.error);});}
async function removePhoto(id){const s=await tx("readwrite");return new Promise((res,rej)=>{const r=s.delete(id);r.onsuccess=res;r.onerror=()=>rej(r.error);});}
function labelFor(device, index){let n=device.label||`カメラ ${index+1}`; const l=n.toLowerCase(); if(/ultra|wide|広角/.test(l)) n+="（広角）"; else if(/tele|望遠/.test(l)) n+="（望遠）"; else if(/front|user|face|前面/.test(l)) n+="（内側）"; else n+="（外側）"; return n;}
async function stopCamera(){state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;}
function timeoutError(label){const error=new Error(label+" timed out");error.name="TimeoutError";return error;}
function requestCamera(constraints){return new Promise((resolve,reject)=>{let complete=false;const timer=setTimeout(()=>{complete=true;reject(timeoutError("Camera request"));},12000);navigator.mediaDevices.getUserMedia({video:constraints,audio:false}).then(stream=>{if(complete){stream.getTracks().forEach(track=>track.stop());return;}complete=true;clearTimeout(timer);resolve(stream);},error=>{if(complete)return;complete=true;clearTimeout(timer);reject(error);});});}
function waitFor(promise,label){return new Promise((resolve,reject)=>{let complete=false;const timer=setTimeout(()=>{complete=true;reject(timeoutError(label));},6000);Promise.resolve(promise).then(value=>{if(complete)return;complete=true;clearTimeout(timer);resolve(value);},error=>{if(complete)return;complete=true;clearTimeout(timer);reject(error);});});}
function cameraErrorMessage(e){const name=e?.name||"UnknownError";if(name==="NotAllowedError"||name==="SecurityError")return "カメラの利用が許可されていません。Safariの設定、またはこのサイトのカメラ許可を確認してください。";if(name==="NotFoundError")return "利用できるカメラが見つかりませんでした。端末を再起動してからお試しください。";if(name==="NotReadableError"||name==="AbortError")return "カメラに接続できませんでした。別のアプリまたはOSがカメラを使用中の場合があります。端末を再起動してから、もう一度お試しください。";if(name==="TimeoutError")return "カメラが12秒以内に応答しませんでした。ページを閉じて開き直すか、端末を再起動してからもう一度お試しください。";return "カメラを起動できませんでした（"+name+"）。下のボタンを押して再試行してください。";}
function setGate(mode,message=""){const gate=$("#cameraGate"),title=$("#gateTitle"),text=$("#gateText"),button=$("#startCameraButton"),note=$("#gateNote");gate.hidden=false;gate.classList.toggle("connecting",mode==="connecting");if(mode==="ready"){title.textContent="Silent Camera";text.textContent="写真はサーバーへ送信されず、この端末だけで処理されます。";button.textContent="カメラを開始";button.disabled=false;note.textContent="ボタンを押すと、ブラウザからカメラ利用の許可を求められます。";}else if(mode==="connecting"){title.textContent="カメラに接続中";text.textContent="カメラを準備しています。しばらくお待ちください。";button.textContent="接続中…";button.disabled=true;note.textContent="画面を閉じずにお待ちください。";}else{title.textContent="カメラに接続されていません";text.textContent=message;button.textContent="もう一度接続する";button.disabled=false;note.textContent="許可済みでも接続に失敗する場合があります。ほかのアプリを完全に閉じてから再試行してください。";}}
async function startCamera(deviceId){ await stopCamera(); $("#controls").hidden=true; setGate("connecting"); try { const videoConstraints=deviceId?{deviceId:{exact:deviceId}}:{facingMode:{ideal:state.facing}}; try{state.stream=await requestCamera(videoConstraints);}catch(firstError){if(deviceId||firstError.name==="NotAllowedError"||firstError.name==="SecurityError"||firstError.name==="TimeoutError")throw firstError;state.stream=await requestCamera(true);} video.srcObject=state.stream; await waitFor(video.play(),"Preview start"); const track=state.stream.getVideoTracks()[0], settings=track.getSettings(), caps=track.getCapabilities?.()||{}; state.deviceId=settings.deviceId; state.facing=settings.facingMode||state.facing; setupZoom(caps,settings); refreshCameras().catch(error=>console.warn("Camera list unavailable:",error)); $("#cameraGate").hidden=true; $("#controls").hidden=false; } catch(e) { await stopCamera(); video.srcObject=null; setGate("error",cameraErrorMessage(e)); console.warn("Camera start failed:",e); } }
function setupZoom(caps, settings){const row=$("#zoomRow"),slider=$("#zoomSlider"); if(caps.zoom){row.hidden=false;slider.min=caps.zoom.min;slider.max=caps.zoom.max;slider.step=caps.zoom.step||.1;slider.value=settings.zoom||caps.zoom.min;$("#zoomValue").value=`${Number(slider.value).toFixed(1)}×`;}else row.hidden=true;}
async function refreshCameras(){const list=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==="videoinput"), sel=$("#cameraSelect");sel.replaceChildren();list.forEach((d,i)=>{const o=new Option(labelFor(d,i),d.deviceId,d.deviceId===state.deviceId,d.deviceId===state.deviceId);sel.add(o);});}
function shutterSound(){if(!state.sound)return;const ac=new (window.AudioContext||window.webkitAudioContext)(),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=1180;g.gain.setValueAtTime(.06,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.08);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+.08);o.addEventListener("ended",()=>ac.close());}
async function capture(){if(!video.videoWidth)return; shutter.disabled=true; try{canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d").drawImage(video,0,0); const blob=await new Promise(r=>canvas.toBlob(r,"image/jpeg",.94)); if(!blob)throw new Error("画像を作成できませんでした");const photo={id:crypto.randomUUID?.()||String(Date.now())+Math.random(),blob,created:Date.now()};try{await putPhoto(photo);}catch(e){state.memoryOnly=true;console.warn("Local photo storage unavailable:",e);}state.photos.unshift(photo);updateGallery();$("#flash").classList.remove("active");void $("#flash").offsetWidth;$("#flash").classList.add("active");shutterSound();}finally{shutter.disabled=false;}}
function url(photo){return URL.createObjectURL(photo.blob)}
function updateGallery(){const last=state.photos[0], img=$("#lastPhoto"), empty=$("#galleryEmpty");if(last){img.src=url(last);img.hidden=false;empty.hidden=true;}else{img.hidden=true;empty.hidden=false;}$("#photoCount").textContent=state.photos.length?"("+state.photos.length+")":"";const grid=$("#galleryGrid");grid.replaceChildren(...state.photos.map(p=>{const b=document.createElement("button"),i=new Image();i.src=url(p);i.alt="撮影した写真を開く";b.append(i);b.onclick=()=>openPhoto(p);return b;}));}
function openPhoto(photo){state.selected=photo;$("#selectedPhoto").src=url(photo);$("#photoDialog").showModal();}
function openSheet(id){$("#scrim").hidden=false;$("#"+id).hidden=false;}
function closeSheet(id){$("#"+id).hidden=true;if([...document.querySelectorAll(".sheet")].every(x=>x.hidden))$("#scrim").hidden=true;}
async function sharePhoto(){const p=state.selected,name="silent-camera-"+new Date(p.created).toISOString().replaceAll(":","-")+".jpg",file=new File([p.blob],name,{type:"image/jpeg"});try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:"写真"});else downloadPhoto();}catch(e){if(e.name!=="AbortError")downloadPhoto();}}
function downloadPhoto(){const p=state.selected,a=document.createElement("a");a.href=url(p);a.download="silent-camera-"+p.created+".jpg";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
$("#menuButton").onclick=()=>{openSheet("menuSheet");$("#menuButton").setAttribute("aria-expanded","true")};$("#termsButton").onclick=()=>openSheet("termsSheet");document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>closeSheet(b.dataset.close));$("#scrim").onclick=()=>document.querySelectorAll(".sheet").forEach(x=>closeSheet(x.id));$("#galleryButton").onclick=()=>openSheet("gallerySheet");$("#shutterButton").onclick=capture;$("#startCameraButton").onclick=()=>startCamera();$("#cameraSelect").onchange=e=>startCamera(e.target.value);$("#flipButton").onclick=()=>{state.facing=state.facing==="user"?"environment":"user";startCamera();};$("#zoomSlider").oninput=async e=>{const v=Number(e.target.value);$("#zoomValue").value=`${v.toFixed(1)}×`;try{await state.stream?.getVideoTracks()[0].applyConstraints({advanced:[{zoom:v}]});}catch{}};$("#soundButton").onclick=()=>{state.sound=!state.sound;const b=$("#soundButton");b.querySelector("span").textContent=state.sound?"ON":"OFF";b.setAttribute("aria-label",`撮影音: ${state.sound?"オン":"オフ"}`);b.title=b.getAttribute("aria-label");};$(".dialog-close").onclick=()=>$("#photoDialog").close();$("#shareButton").onclick=sharePhoto;$("#downloadButton").onclick=downloadPhoto;$("#deleteButton").onclick=async()=>{if(state.selected&&confirm("この端末内の一時保存写真を削除しますか？")){try{if(!state.memoryOnly)await removePhoto(state.selected.id);}catch(e){console.warn("Local deletion failed:",e);}state.photos=state.photos.filter(p=>p.id!==state.selected.id);$("#photoDialog").close();updateGallery();}};
window.addEventListener("beforeunload",stopCamera);navigator.mediaDevices?.addEventListener?.("devicechange",refreshCameras);(async()=>{try{state.photos=await readPhotos();}catch(e){state.photos=[];state.memoryOnly=true;console.warn("Local photo storage unavailable:",e);}updateGallery();if(!navigator.mediaDevices?.getUserMedia){setGate("error","このブラウザはカメラ機能に対応していません。");$("#startCameraButton").disabled=true;return;}setGate("ready");})();
